name: Request content support
description:  Request support for content creation from the Programs Team. 
title: "[Content Request]: "
assignees:
  - elisemoe
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out the content request form!
        
  - type: input
    id: audience
    attributes:
      label: Target Audience
      description: Audience selection criteria, list, etc.
      placeholder: Students in India
    validations:
      required: true
      
  - type: input
    id: dates
    attributes:
      label: Publish by date
      description: Provide date content will go live.
      placeholder: ex. 06/01/2021
    validations:
      required: true
      
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Email
        - Newsletter Mention
        - Blog Post
        - Social Campaign
        - Video Production
        - Community Share Kit
    validations:
      required: true
 
  - type: textarea
    id: cta
    attributes:
      label: Call to Action
      placeholder: "What is the one action you would like your audience to take after seeing your content? Is there a link?"
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes
      description: Please link any notes, drafts, or related issues. If you have requested a social campaign, specify how many posts you are requesting and the timeframe for the campaign. If you have requested a share kit, please specify the audience who will receive the kit.
      placeholder: 
    validations:
      required: true
